### ISSUE TITLE
Fork from particular block number

### ISSUE THREAD

**Issue by sosoxuc** [Ackee-Blockchain/woke#247]
Is the Fork from particular block number supported? Did not find that in configs

**Comment by sosoxuc** [comment]
Just checked and you are using other systems under the hood

HardHat supports that as I see
  --fork             	The URL of the JSON-RPC server to fork from 
  --fork-block-number	The block number to fork from

**Comment by hacker-DOM** [comment]
@michprev It seems to me that is supported right? Quoting https://ackeeblockchain.com/woke/docs/latest/testing-framework/migrating-from-ape-and-brownie/#configuring-networks:

```python
@default_chain.connect(
    accounts=20,  # number of accounts to generate
    chain_id=1337,  # chain ID
    fork="https://eth-mainnet.alchemyapi.io/v2/...@12345678",  # fork from a block
    hardfork="london",  # hardfork to use
)
```

**Comment by michprev** [comment]
Yes, `fork="FORK_URI@BLOCK_NUMBER"` is the way for Anvil and Ganache.
Hardhat does not support CLI options, so these parameters must be set in the Hardhat config file.

**Comment by michprev** [comment]
Closing this as I don't see any benefit of adding an extra parameter instead of using the `url@number` syntax. Feel free to reopen if you encounter any scenario when the described approach cannot be used or is limiting.
