### ISSUE TITLE
Setup poetry / pdm

### ISSUE THREAD

**Issue by michprev** [Ackee-Blockchain/woke#76]
Instead of setuptools it may be a good idea to use either [poetry](https://python-poetry.org) or [pdm](https://pdm.fming.dev/latest/).
- due to eth-brownie pinned dependencies (https://github.com/eth-brownie/brownie/issues/1516) it is not currently possible to use poetry
    - setting `BROWNIE_LIB=1` does not help (and also does not feel like the best solution)
- pdm feels too early and works with [PEP 582](https://peps.python.org/pep-0582/) which is still a draft

**Comment by hacker-DOM** [comment]
Pdm works great, never had any problems related to it, has great implementation and documentation, easy to use custom README (`README.adoc`), and most importantly, it includes all non-python files by default.
Before, with setuptools, I would need `setup.py` with many config options (`packages`, `data_files`, `package_data`...), `MANIFEST.in` etc. With Pdm, you just need `pyproject.toml` and so far it has always done what I expected it to. Strongly recommend!
Here is an example that deployed woke with brownie: https://github.com/hacker-DOM/woke/blob/d86e8ba23c4a523ba3aab196a2e1b474e5922dbf/woke/pyproject.toml

**Comment by michprev** [comment]
Using poetry from Woke 2.0
