### ISSUE TITLE
Show ascii spinner / waiting animation while fuzzing

### ISSUE THREAD

**Issue by michprev** [Ackee-Blockchain/woke#87]
We should somehow inform the user that the fuzzer is fuzzing. While not is passive mode (i.e. `woke fuzz --passive`) we should print a message like `Fuzzing...` with an ASCII spinner (https://stackoverflow.com/questions/2685435/cooler-ascii-spinners). Maybe, we could also use indeterminate progress from rich library https://rich.readthedocs.io/en/stable/progress.html#indeterminate-progress.

**Comment by Aragahara** [comment]
Implemented in #108
