### ISSUE TITLE
Support additional dev chains in fuzzer

### ISSUE THREAD

**Issue by michprev** [Ackee-Blockchain/woke#89]
Brownie supports a large number of development chains but our fuzzer currently only works with Ganache. It should not be difficult to provide support for more dev chains. See https://github.com/eth-brownie/brownie/blob/master/brownie/data/network-config.yaml (section `development`).

The revelant code
https://github.com/Ackee-Blockchain/woke/blob/6fb8b18b59aa8720c51287ecf4460c092dfd95de/woke/fuzzer/fuzzer.py#L30-L39

`cmd = "ganache-cli"` can be replaced by `cmd = active_network["cmd"]`

`"development"` identifier in the `CONFIG.set_active_network` call should be configurable by the end user (i.e. `woke fuzz --network anvil`)

**Comment by Aragahara** [comment]
Anvil (0.1.0) and ethnode (0.1.1) (geth-dev) do not work with brownie (1.19.0) in default configurations nor with some custom confs we tested, but the implementation should allow for custom ganache networks and also other dev chains in the future should brownie support them.
